package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_UNIQUENESS_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ade/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u241/331/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, December 11, 2019 10:23:07 AM UTC
*/

public interface ID_UNIQUENESS_POLICY_ID
{

  /**
	 * The value representing ID_UNIQUENESS_POLICY_ID.
	 */
  public static final int value = (int)(18L);
}
