# mysql 5 驱动不同 com.mysql.jdbc.Driver
spring:
  datasource:
    # mysql 配置
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
    # oracle 配置
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.20.22.231:1521/orcl
    username: drgsplatform_sq
    password: drgsplatform_sq

# mysql 8 驱动不同 com.mysql.cj.jdbc.Driver、需要增加时区配置 serverTimezone=UTC

# 配置日志
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mapper/read/*.xml
    - classpath*:mapper/write/*.xml
