package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/ade/jenkins/workspace/8-2-build-windows-amd64-cygwin/jdk8u241/331/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Wednesday, December 11, 2019 10:23:05 AM UTC
*/

public interface TAG_POLICIES
{

  /**
     * A profile component containing the sequence of QoS policies exported
     * with the object reference by an object adapter.
     */
  public static final int value = (int)(2L);
}
